#!/bin/bash
set -x

# Configure Git to only push the current branch
git config --global push.default simple

# Remove .gitignore and replace with the production version
rm -f .gitignore
cp scripts/prodignore .gitignore
cat .gitignore

# Add the Linode production server as a remote repository
git remote add production ssh://chad@45.79.2.80:/home/chad/project/crypto-watch

# Add and commit all the static files generated by the Gatsby build
git add . && git commit -m "build"

# Push all changes to the Linode production server
git push -f production HEAD:refs/heads/master
